version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: python:3.9 # Use a Python 3 image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install --upgrade docker-py
            pip install docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
